version: 2.1

jobs:
  test:
    parameters:
      node-version:
        type: string
    docker:
      - image: cimg/node:<< parameters.node-version >>
    environment:
      # Must be used for running the webpack@4 tests on node >= 17
      NODE_OPTIONS: --openssl-legacy-provider
    steps:
      - checkout
      - run: |
          echo "Node version: $(node --version)"
          echo "NPM version:  $(npm --version)"
          npm install
          npm run ci

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              node-version:
                - "current"
                - "lts"
          name: test-on-node-<< matrix.node-version >>
